services:
  webapp:
    image: golang:1.23
    container_name: webapp
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    restart: unless-stopped
    command: bash -c "cd webapp && go run main.go"
    environment:
      WEBAPP_PORT: "${WEBAPP_PORT}"
    volumes:
      - ./:/go/
    networks:
      - api
    depends_on:
      - api

  api:
    image: golang:1.23
    container_name: api
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    command: bash -c "cd api && go run main.go"
    environment:
      API_PORT: "${API_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
    volumes:
      - ./:/go/
    networks:
      - db
      - api
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    privileged: true
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - my-db:/var/lib/mysql
    networks:
      - db

volumes:
  my-db:

networks:
  db:
  api:  
